language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1.100
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x Scripts
  - chmod -R a+x src
script:
  - ./Scripts/build.sh
  - ./Scripts/test.sh
after_success:
  - ./Scripts/pack.sh
notifications:
  email:
    recipients:
      - filap4@gmail.com
    on_success: never
    on_failure: always



