name: NuGet Generation Auth

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  push-package:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
        
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o Package  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Package/SCL.Auth.*.nupkg --api-key ${{secrets.SCL_AUTH_PACKAGES_KEY}} --skip-duplicate --source https://api.nuget.org/v3/index.json
          
