name: NuGet Generation Auth

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Setup .NET Core @ Latest
        run: dotnet nuget add source https://nuget.pkg.github.com/flapek/index.json -n github -u flapek -p ${{secrets.Packages_TOKEN}} 
        
      - name: Build solution and generate NuGet package
        run: |  
          cd ./src/SCL
          dotnet pack -c Release -o Package  

      - name: Push generated package to GitHub registry
        run: |
          cd ./src/SCL/Package
          dotnet nuget push *.nupkg --skip-duplicate --no-symbols true
