name: NuGet Generation Auth

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/flapek/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.Packages_TOKEN}}        

      - name: Build solution and generate NuGet package
        run: |  
          cd ./src/SCL
          dotnet pack -c Release -o Package  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./src/SCL/Package/*.nupkg --skip-duplicate --no-symbols true
